config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  
  resources :user_management
  post '/user_management/:id', to: 'user_management#create', as: 'create_by_management'
  patch '/user_management/:id', to: 'user_management#update', as: 'update_by_management'
  delete '/user_management/:id', to: 'user_management#destroy', as: 'delete_by_management'
  
  resources :sales
  resources :products
  resources :customers

  root to: 'dashboard#index'
end

app/controllers/user_management_controller.rb
class UserManagementController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  authorize_resource :class => :user_management

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end
  
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_management_path(@user), notice: "User succesfully created!" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation) 
    end

    if @user.update_attributes(user_params)
      redirect_to user_management_path(@user), notice: "User succesfully updated."
    else
      render :edit
    end
  end

  def destroy
    if current_user.id != params[:id].to_i
      if @user.destroy
        redirect_to user_management_index_path, notice: "User has been destroyed"
      else
        render :index, notice: "Failed to delete user"
      end
    else
      redirect_to user_management_index_path, notice: "Failed to delete user"
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(
        :email, :password, :password_confirmation, user_profile_attributes: [:id, :name, :phone, :gender, :picture]
      )
    end
end

app/helpers/user_management_helper.rb
module UserManagementHelper
end

app/views/user_management/_form.html.erb
<%= nested_form_for([user, user.with_user_profile], url: action) do |f| %>
  <%= render "devise/shared/error_messages", resource: user %>

  <%= f.fields_for :user_profile do | up | %>

    <figure>
      <%= image_tag set_img(user) %>
    </figure>

    <div>
      <%= up.label :picture %>
      <%= up.file_field :picture %>
    </div>

    <div>
      <%= up.label :name %>
      <%= up.text_field :name %>
    </div>

    <div>
      <%= up.label :phone %>
      <%= up.text_field :phone %>
    </div>

    <div>
      <%= up.label :gender %>
      <%= up.text_field :gender %>
    </div>

  <% end %>

  <%= f.email_field :email, required: true, autofocus: true %>

    <div>
    <%= f.label :password %>
    <%= f.password_field :password,
        hint: "leave it blank if you don't want to change it",
        required: false,
        input_html: { autocomplete: "new-password" } 
    %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation,
          required: false,
          input_html: { autocomplete: "new-password" } 
    %>
  </div>

  <div>
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/user_management/edit.html.erb
<h2>Edit User</h2>

<%= render "form", user: @user, action: update_by_management_path %>

<%= link_to "Back", :back %>

app/views/user_management/index.html.erb
<header class="content__title">
  <h1>users</h1>
</header>

<div class="toolbar">
  <div class="toolbar__label"><span class="hidden-xs-down">Total </span><%= @users.all.size %> users</div>

  <div class="actions">
    <%= link_to 'New User', new_user_management_path %>
  </div>

  <div class="toolbar__search">
    <input type="text" placeholder="Search...">
    <i class="toolbar__search__close zmdi zmdi-long-arrow-left" data-ma-action="toolbar-search-close"></i>
  </div>
</div>

<div class="row lightbox photos">
  <% @users.each do |user| %>
    <%= link_to user_management_path(user), class: "col-md-2 col-4" do %>
      <div class="lightbox__item photos__item">
        <%= user.user_profile.name %>
        <%= image_tag set_img(user) %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/user_management/new.html.erb
<%= render "form", user: @user, action: user_management_index_path %>

app/views/user_management/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture:</strong>
  <%= image_tag set_img(@user) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.user_profile.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.user_profile.phone %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.user_profile.gender %>
</p>

<%= link_to 'Edit', edit_user_management_path(@user) %> |
<%= link_to 'Back', user_management_index_path %> |
<%= link_to "Cancel account", delete_by_management_path(@user), data: { confirm: "Are you sure?" }, method: :delete %>