config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  
  resources :user_management
  post '/user_management/:id', to: 'user_management#create', as: 'create_by_management'
  patch '/user_management/:id', to: 'user_management#update', as: 'update_by_management'
  delete '/user_management/:id', to: 'user_management#destroy', as: 'delete_by_management'
  
  resources :sales
  resources :products
  resources :customers

  root to: 'dashboard#index'
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :customer
  has_one_attached :outgoing_invoice

  attr_accessor :quantiti
  store_accessor :data, :product

  before_save :prepare_attrs_sale_products, :clear_products_list

  def clear_products_list
    return if self.id.nil?

    Sale.find(self.id).product.clear
  end

  def prepare_attrs_sale_products
    return if /:id=>\d{1,}, :quantiti=>\d{1,}/.match(self.product.first)

    self.product.each_with_index do |product, i| 
      product.delete!("}]")
      product.concat(", :quantiti=>#{self.quantiti[i]}}]")
    end
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  load_and_authorize_resource
  before_action :set_sale, only: %i[ show edit update destroy ]

  def index
    @sales = Sale.all
  end

  def show
  end

  def new
    @sale = Sale.new
    @product_ids = Product.all.map(&:id)
    @iterator_product_ids = 0
  end

  def edit
    @product_ids = Product.all.map(&:id)
    @iterator_product_ids = 0
  end

  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to sale_url(@sale), notice: "Sale was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sale_url(@sale), notice: "Sale was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to sales_url, notice: "Sale was successfully destroyed." }
    end
  end

  private
    def set_sale
      @sale = Sale.find(params[:id])
    end

    def sale_params
      params.require(:sale).permit(
        :outgoing_invoice,
        :customer_id,
        :date_sale,
        product: [],
        quantiti: []
      )
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= simple_form_for sale do |form| %>
  <% if sale.errors.any? %>
    <div>
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id  %>
  </div>

  <div> 
    <%= 
      form.input :product,
      collection: Product.all.map { |product| [ product.name, [id: product.id] ] },
      include_hidden: false,
      input_html: { multiple: true } 
    %>

    <% Product.all.size.times do %>
      <%= form.label Product.find(@product_ids[@iterator_product_ids]).name %>
      <%= form.number_field :quantiti, multiple: true %>
      <% @iterator_product_ids += 1 %>
    <% end %>
  </div>

  <div>
    <%= form.label :date_sale %>
    <%= form.datetime_select :date_sale %>
  </div>

  <div>
    <%= form.label :outgoing_invoice %>
    <%= form.file_field :outgoing_invoice %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<div class="card">
  <div class="card-body">
    <header class="content__title">
      <h4 class="card-title">Sales</h4>

      <div class="actions">
        <%= link_to new_sale_path, class: "btn btn-success btn--icon-text" do %>
          <i class="zmdi zmdi-arrow-forward"></i> New Sale
        <% end %>
      </div>
    </header>

    <table class="table mb-0">
      <thead>
        <tr>
          <th>Customer</th>
          <th>Date sale</th>
        </tr>
      </thead>
      <tbody>
        <% @sales.each do |sale| %>
          <tr>
            <td><%= sale.customer.name %></td>
            <td><%= sale.date_sale %></td>
            <td><%= link_to 'Show products', sale %></td>
            <td><%= link_to 'Details', sale %></td>
            <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
            <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @sale.customer %>
</p>

<p>
  <strong>Products:</strong>
  <%= @sale.product %>
</p>

<p>
  <strong>Date sale:</strong>
  <%= @sale.date_sale %>
</p>

<p>
  <strong>Outgoing Invoice</strong>
  <%= image_tag set_img(@sale) %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>