config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  
  resources :user_management
  post '/user_management/:id', to: 'user_management#create', as: 'create_by_management'
  patch '/user_management/:id', to: 'user_management#update', as: 'update_by_management'
  delete '/user_management/:id', to: 'user_management#destroy', as: 'delete_by_management'
  
  resources :sales
  resources :products
  resources :customers

  root to: 'dashboard#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>ManageTradein</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
  </head>

  <body data-ma-theme="green">
    <main class="main">
      <div class="page-loader">
        <div class="page-loader__spinner">
          <svg viewBox="25 25 50 50">
            <circle cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
          </svg>
        </div>
      </div>

      <header class="header">
        <div class="navigation-trigger hidden-xl-up" data-ma-action="aside-open" data-ma-target=".sidebar">
          <div class="navigation-trigger__inner">
            <i class="navigation-trigger__line"></i>
            <i class="navigation-trigger__line"></i>
            <i class="navigation-trigger__line"></i>
          </div>
        </div>

        <div class="header__logo hidden-sm-down">
          <h1><%= link_to "Manage Trade-In", root_path %></h1>
        </div>
      </header>

      <aside class="sidebar">
        <div class="scrollbar-inner">
          <div class="user">
            <div class="user__info" data-toggle="dropdown">
              <%= image_tag "user_profile.jpg", class: "user__img" %>
              <div>
                <div class="user__name"><%= current_user.user_profile.name %></div>
                <div class="user__email"><%= current_user.email %></div>
              </div>
            </div>

            <div class="dropdown-menu">                          
              <%= link_to "View Profile", edit_user_registration_path, class: "dropdown-item" %>
              <% if can? :read, :user_management %>
                <%= link_to "New User", new_user_management_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>

          <ul class="navigation">
            <li>
              <%= link_to dashboard_index_path do %>
                <i class="zmdi zmdi-home"></i> Dashboard
              <% end %>
            </li>

            <li>
              <%= link_to customers_path do %>
                <i class="zmdi zmdi-face"></i> Customers
              <% end %>
            </li>

            <li>
              <%= link_to products_path do %>
                <i class="zmdi zmdi-fire"></i> Products
              <% end %>
            </li>

            <li>
              <%= link_to sales_path do %>
                <i class="zmdi zmdi-money"></i> Sales
              <% end %>
            </li>

            <li>
              <%= link_to user_management_index_path do %>
                <i class="zmdi zmdi-accounts"></i> User Management
              <% end %>
            </li>
          </ul>
        </div>
      </aside>

      <section class="content">
        <div class="content__inner">                    
          <%= yield %>
        </div>

        <footer class="footer hidden-xs-down">
          <p>© Manage Trade-In</p>
        </footer>
      </section>
    </main>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>ManageTradein</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'devise' %>
  </head>

  <body data-ma-theme="green">
    <div class="login">
      <%= yield %>                
    </div>
    
    <%= javascript_include_tag 'devise' %>
  </body>
</html>